CPS = read.csv(choose.files())
sort(table(CPS$Industry))
sort(table(CPS$State))
table(CPS$Citizenship)
table(CPS$Race,CPS$Hispanic)
summary(CPS)
table(CPS$Region, is.na(CPS$Married))
table(CPS$Citizenship, is.na(CPS$Married))
table(CPS$Sex, is.na(CPS$Married))
table(CPS$Age, is.na(CPS$Married))
#table(CPS$State, is.na(CPS$MetroAreaCode))
table(CPS$Region, is.na(CPS$MetroAreaCode))
#tapply(is.na(CPS$MetroAreaCode), CPS$State, mean)
MetroAreaMap = read.csv(choose.files())
CountryMap = read.csv(choose.files())
CPS = merge(CPS, MetroAreaMap, by.x="MetroAreaCode", by.y="Code", all.x=TRUE)
str(CPS)
sort(summary(CPS$MetroArea))
sort(tapply( CPS$Hispanic, CPS$MetroArea, mean))
sort(tapply(CPS$Race=="Asian", CPS$MetroArea, mean))
sort(tapply(CPS$Education == "No high school diploma", CPS$MetroArea, mean,na.rm=TRUE))
CPS = merge(CPS, CountryMap, by.x="CountryOfBirthCode", by.y="Code", all.x=TRUE)
sort(summary(CPS$Country))
table(CPS$MetroArea == "New York-Northern New Jersey-Long Island, NY-NJ-PA", CPS$Country != "United States")
table(CPS$MetroArea, CPS$Country=="Somalia")